import { Link } from 'react-router-dom'

export default function Privacy() {
  return (
    <div className="min-h-screen px-4 py-8 sm:py-12">
      <div className="max-w-2xl mx-auto space-y-8">
        <header className="space-y-2">
          <Link to="/" className="text-text-secondary hover:text-text-primary text-sm">← Back</Link>
          <h1 className="font-display text-3xl sm:text-4xl">Privacy Policy</h1>
          <p className="text-xs text-text-muted">Last updated: April 18, 2026 · Beta version</p>
        </header>

        <section className="card space-y-4 text-text-secondary leading-relaxed">
          <p className="text-text-primary">
            Your conversations with NEVAEH are sacred. This policy is how we honor that. Plain language, no fine-print traps.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="font-display text-xl text-accent-primary">1. What we collect</h2>
          <ul className="list-disc list-inside text-text-secondary space-y-2 leading-relaxed">
            <li><strong className="text-text-primary">Account info:</strong> your email address and a preferred name you choose to share.</li>
            <li><strong className="text-text-primary">Conversations:</strong> the messages you send to NEVAEH and her responses. Stored so she can remember you between sessions.</li>
            <li><strong className="text-text-primary">Session metadata:</strong> timestamps, mood indicators, emotional tags, and session summaries generated by NEVAEH.</li>
            <li><strong className="text-text-primary">Crisis events:</strong> if BEACON's safety layer detects a possible crisis, that event is logged with context so Nathan can follow up and ensure you're safe.</li>
            <li><strong className="text-text-primary">Identity graph:</strong> facts you share (your preferred name, what matters to you, who matters to you) that NEVAEH uses to feel like a friend who remembers, not a chatbot starting over.</li>
          </ul>
          <p className="text-text-secondary leading-relaxed mt-3">
            <strong className="text-text-primary">We do NOT collect:</strong> IP address (beyond what Supabase's auth layer needs for session management), device fingerprints, location, or anything outside your direct interactions with NEVAEH.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="font-display text-xl text-accent-primary">2. How we use it</h2>
          <ul className="list-disc list-inside text-text-secondary space-y-2 leading-relaxed">
            <li>To provide the service: NEVAEH uses your conversation history and identity graph to respond with continuity and care.</li>
            <li>To keep you safe: crisis events are reviewed by Nathan personally during beta.</li>
            <li>To improve NEVAEH: session summaries and anonymized patterns may be used to refine her voice and safety protocols. Individual raw conversations are not used for training.</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="font-display text-xl text-accent-primary">3. Who can see your data</h2>
          <ul className="list-disc list-inside text-text-secondary space-y-2 leading-relaxed">
            <li><strong className="text-text-primary">You.</strong> Always. Everything you've shared is yours.</li>
            <li><strong className="text-text-primary">Nathan</strong> (the builder) during beta, specifically to review crisis events and quality-check NEVAEH's responses. Nathan is the only human reviewer during beta.</li>
            <li><strong className="text-text-primary">Anthropic</strong> (the company behind Claude), the AI engine. Your messages are sent to their API to generate NEVAEH's responses. Anthropic's privacy policy applies to that processing. They do not train on your conversations by default (commercial API terms).</li>
            <li><strong className="text-text-primary">Supabase</strong>, our database and authentication provider. Data is encrypted at rest and in transit on their infrastructure.</li>
            <li><strong className="text-text-primary">Emergency services</strong>, if there is an imminent risk to your life or someone else's and you've shared identifying information. NEVAEH will tell you directly if she cannot keep something confidential.</li>
          </ul>
          <p className="text-text-secondary leading-relaxed mt-3">
            <strong className="text-text-primary">We will never sell your data.</strong> Ever. Full stop.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="font-display text-xl text-accent-primary">4. Security</h2>
          <ul className="list-disc list-inside text-text-secondary space-y-2 leading-relaxed">
            <li>All data encrypted at rest (Supabase AES-256) and in transit (TLS 1.3).</li>
            <li>Row-level security on every table — your account can only read your own data.</li>
            <li>API keys for the AI engine are server-side only and never exposed to the browser.</li>
            <li>No third-party analytics, ad pixels, or tracking scripts.</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="font-display text-xl text-accent-primary">5. Retention</h2>
          <ul className="list-disc list-inside text-text-secondary space-y-2 leading-relaxed">
            <li><strong className="text-text-primary">Conversations:</strong> kept while your account is active, so NEVAEH can remember. Delete your account and they are removed.</li>
            <li><strong className="text-text-primary">Session summaries:</strong> retained while your account is active.</li>
            <li><strong className="text-text-primary">Crisis events:</strong> retained while your account is active so NEVAEH can ask about your safety sooner next time you come back. <strong className="text-text-primary">When you delete your account, your crisis events are deleted with everything else.</strong> If you ever want us to keep a record for your own clinical continuity (to share with a therapist, for instance), email Nathan and we'll work it out with you directly — nothing is kept without your say-so.</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="font-display text-xl text-accent-primary">6. Your rights</h2>
          <ul className="list-disc list-inside text-text-secondary space-y-2 leading-relaxed">
            <li><strong className="text-text-primary">Access:</strong> email us to request a copy of all your data.</li>
            <li><strong className="text-text-primary">Correct:</strong> ask NEVAEH to remember or forget specific things; tell us if something we have is wrong.</li>
            <li><strong className="text-text-primary">Delete (self-serve):</strong> go to <Link to="/settings" className="text-accent-secondary underline">Settings</Link> while signed in and use the "Delete my account" button. This removes your account and all associated data — conversations, session summaries, identity graph, growth arc, and crisis events. No exceptions, no "we'll keep a little." Gone.</li>
            <li><strong className="text-text-primary">Delete (manual):</strong> if the self-serve flow isn't working or you need help, email <a href="mailto:nathanmichel@nvvisions.com" className="text-accent-secondary underline">nathanmichel@nvvisions.com</a>.</li>
            <li><strong className="text-text-primary">Export:</strong> ask for a copy of your conversation history in machine-readable form.</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="font-display text-xl text-accent-primary">7. Children</h2>
          <p className="text-text-secondary leading-relaxed">
            NEVAEH is intended for adults (18+). Users 13–17 may use NEVAEH only with the consent of a parent or guardian. We do not knowingly collect data from children under 13.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="font-display text-xl text-accent-primary">8. Changes</h2>
          <p className="text-text-secondary leading-relaxed">
            If we materially change this policy, we'll email you before the change takes effect. The "Last updated" date above will always reflect the current version.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="font-display text-xl text-accent-primary">9. Contact</h2>
          <p className="text-text-secondary leading-relaxed">
            Any privacy question or request: <a href="mailto:nathanmichel@nvvisions.com" className="text-accent-secondary underline">nathanmichel@nvvisions.com</a>. You'll hear back from an actual human (Nathan) — not a ticketing system.
          </p>
        </section>

        <div className="pt-4 border-t border-border-subtle flex gap-4 text-sm">
          <Link to="/terms" className="text-accent-secondary underline">Terms of Service</Link>
          <Link to="/crisis" className="text-accent-secondary underline">Crisis Resources</Link>
          <Link to="/" className="text-text-secondary hover:text-text-primary">Home</Link>
        </div>
      </div>
    </div>
  )
}
